import random, time 

def story():
    print('Once upon a time, people looked at the sun in hope and warmth...')
    time.sleep(5)
    print('then, once upon a time, it burned the eyes of all those pitiful fools that looked upon it with hope and warmth...')
    time.sleep(9)
    print('now the sands that encase the earth are filled with the ash of all the souls that once lived...')
    time.sleep(8)
    print('except for a few...')
    time.sleep(5)
    print('a tiny amount of people...')
    time.sleep(5)
    print('and after generations bloody hands and smoked flesh...')
    time.sleep(5)
    print('roots could finally sprout...')
    time.sleep(4)
    print('and the little life that spread the Earth...')
    time.sleep(4)
    print('started adapting...')
    time.sleep(4)
    print('villages rised and sands shifted...')
    time.sleep(4)
    print('but the scars are stil lying in wait...')
    time.sleep(4)
    print('still hunger...')
    time.sleep(4)
    print('still hunt...')
    time.sleep(4)
    print('and those generations of fight and will...')
    time.sleep(4)
    print('fuels the hives of flesh...')
    time.sleep(7)
    print('not even the heat of hell can wipe the hate and filth off the flesh of man')

story()